language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install gcc libffi-dev libldap2-dev libsasl2-dev libssl-dev python-dev
install:
- pip install --upgrade -e .
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: opennode
  password:
    secure: p6ainKHGPPYnUGNvjSLeR/gPd3dsF3ba46UEcIVeGzR16qB0J5rmAmN/DuJY8yaSfXvLBFzl+cQyR4wfc4vRRsg1uz8ZVgJ5atbbeEvZz064jcuF9kxKpJOK3ZwBrk5740OuMLsXClQPOcaKptZ8yFXY1WIIVjrFhw2Ntc40m98hu/VAy390aHqM2wFj4gfrubpEnsY3HmaZl9/7gH6liEtxXXjLG14R1uS2ivgSXowFZOCNwZ/3xce4DvHSdH+KOMI45qV78vRx05Hr15JVQAoSFpyvziLdSP+sSRTOj/TiHbnzCrwbWVTPEWQ20/iZ+a5BkFYM/jXrg0mKpOBfCt/Bfx/phTiHZK+45E3MCNxpZ20Nshm6DALn0ONWUvK0LaJN1bATt05Yojev7hnBGjRDBvGMsF8+tsIWEihPDR9x9EXC6+G0fLePPH2mHx0N42OQCYCW8IlHRo0wX6lVILNj1p/y18VFhNVMuritW9ZnJsK4XrvXgw7OA0CFvw7EeyT1NEgtAglXEgkdo2EiZ3naVGP3Ryqwexxj2+DyKIoDO7K7SUvW3YEH4vlrsVjmCyo/ah236x8XXy/tQGdgRp1celBUmFrfWzrdbwIrDcMUzBTB2iRKyUJtAsgEFJuU+Su2ToVW+GaYpBVoi2lrcWV6Tl26hK49rqW/cxjP7Ww=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: opennode/waldur-mastermind
